#!/bin/bash
# Quick Start Guide pour API Keys Implementation

echo "🚀 Quick Start - API Keys Implementation"
echo "=============================================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}📋 Available Commands:${NC}\n"

echo -e "${GREEN}1. Start Backend (Development Mode)${NC}"
echo "   cd backend && npm run start:dev"
echo ""

echo -e "${GREEN}2. Start Frontend (Development Mode)${NC}"
echo "   cd frontend && npm run dev -- -p 3000"
echo ""

echo -e "${GREEN}3. Test API Endpoints (Node.js)${NC}"
echo "   node test-complete-api-keys.js"
echo ""

echo -e "${GREEN}4. Open Prisma Studio (View Database)${NC}"
echo "   cd backend && npx prisma studio"
echo ""

echo -e "${GREEN}5. Run Playwright Tests${NC}"
echo "   npx playwright test tests/api-keys-complete-flow.spec.ts"
echo ""

echo -e "${YELLOW}📚 Documentation Files:${NC}"
echo "   • API_KEYS_IMPLEMENTATION_REPORT.md - Full Report"
echo "   • INTEGRATION_GUIDE_API_KEYS.md - How to Integrate"
echo "   • ARCHITECTURE_DIAGRAMS.md - Technical Diagrams"
echo ""

echo -e "${BLUE}🧪 Test API Keys Workflow:${NC}"
echo ""
echo "Step 1: Start Backend"
echo "  cd backend && npm run start:dev"
echo "  ✅ Wait for: '🚀 Application démarrée sur http://localhost:3001'"
echo ""

echo "Step 2: Test Endpoints (in another terminal)"
echo "  node test-complete-api-keys.js"
echo "  ✅ Should see all tests passed"
echo ""

echo "Step 3: Start Frontend"
echo "  cd frontend && npm run dev -- -p 3000"
echo "  ✅ Wait for: 'ready - started server on 0.0.0.0:3000'"
echo ""

echo "Step 4: Test in Browser"
echo "  • Go to http://localhost:3000"
echo "  • Login with your credentials"
echo "  • Navigate to Settings > API Keys"
echo "  • Fill in API keys and select provider/model"
echo "  • Click 'Enregistrer les clés LLM'"
echo ""

echo "Step 5: Verify Data in Database"
echo "  cd backend && npx prisma studio"
echo "  • Go to ai_settings table"
echo "  • Find your user record"
echo "  • Check defaultModel and defaultProvider fields"
echo ""

echo -e "${BLUE}🔍 Key Endpoints:${NC}"
echo ""
echo "Public (No Auth):"
echo "  POST /api/api-keys/test/gemini"
echo "  POST /api/api-keys/test/openai"
echo "  POST /api/api-keys/test/deepseek"
echo ""
echo "Protected (JWT Required):"
echo "  GET  /api/ai-billing/api-keys/user"
echo "  PUT  /api/ai-billing/api-keys/user"
echo ""

echo -e "${BLUE}📝 Default Models Supported:${NC}"
echo ""
echo "OpenAI:"
echo "  • gpt-4o (Recommended)"
echo "  • gpt-4-turbo"
echo "  • gpt-3.5-turbo"
echo ""
echo "Google Gemini:"
echo "  • gemini-2.0-flash (Latest)"
echo "  • gemini-1.5-pro"
echo "  • gemini-pro"
echo ""
echo "DeepSeek:"
echo "  • deepseek-chat (Recommended)"
echo "  • deepseek-coder"
echo ""
echo "Anthropic (Claude):"
echo "  • claude-3-5-sonnet-20241022 (Latest)"
echo "  • claude-3-opus-20240229"
echo ""

echo -e "${BLUE}✅ Implementation Checklist:${NC}"
echo ""
echo "Backend:"
echo "  ✅ DTO updated with defaultModel and defaultProvider"
echo "  ✅ Endpoints working and tested"
echo "  ✅ Database schema supports fields"
echo ""
echo "Frontend:"
echo "  ✅ New component created (api-keys-enhanced.tsx)"
echo "  ✅ Provider and model selection working"
echo "  ✅ API integration complete"
echo ""
echo "Tests:"
echo "  ✅ Node.js tests passing"
echo "  ✅ Playwright tests configured"
echo ""

echo -e "${BLUE}❓ Troubleshooting:${NC}"
echo ""
echo "Backend won't start:"
echo "  • Check if port 3001 is available: lsof -i :3001"
echo "  • Check NODE_ENV and .env file"
echo "  • Check database connection"
echo ""
echo "Frontend won't load API Keys page:"
echo "  • Check NEXT_PUBLIC_API_URL in .env.local"
echo "  • Verify backend is running"
echo "  • Check browser console for errors"
echo ""
echo "API keys not saving:"
echo "  • Verify JWT token is valid"
echo "  • Check backend logs for errors"
echo "  • Verify database permissions"
echo ""

echo -e "${BLUE}🎉 Next Steps:${NC}"
echo ""
echo "1. Start the application"
echo "2. Create a test user"
echo "3. Go to Settings > API Keys"
echo "4. Add API keys and select provider/model"
echo "5. Click Save"
echo "6. Verify data in Prisma Studio"
echo "7. Ready for integration with rest of app!"
echo ""

echo "=============================================="
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo ""
