import { DocumentBuilder } from '@nestjs/swagger';

export const swaggerConfig = new DocumentBuilder()
  .setTitle('CRM Immobilier API')
  .setDescription('API complète du CRM Immobilier avec 18 modules')
  .setVersion('1.0')
  .addBearerAuth()
  .addTag('auth', 'Authentification')
  .addTag('users', 'Gestion utilisateurs')
  .addTag('properties', 'Gestion biens immobiliers')
  .addTag('prospects', 'Gestion prospects')
  .addTag('communications', 'Email, SMS, WhatsApp')
  .addTag('documents', 'Upload et analyse documents')
  .addTag('appointments', 'Agenda et rendez-vous')
  .addTag('prospecting', 'Prospection intelligente')
  .addTag('validation', 'Validation données')
  .addTag('matching', 'Matching IA')
  .addTag('analytics', 'Statistiques et KPIs')
  .addTag('campaigns', 'Campagnes marketing')
  .addTag('dashboard', 'Dashboard principal')
  .addTag('integrations', 'APIs externes')
  .addTag('settings', 'Paramètres')
  .addTag('tasks', 'Gestion tâches')
  .addTag('ai-metrics', 'Tracking ROI IA')
  .build();
